name: Deploy Static Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Build Directory
        run: |
          mkdir -p dist
          cp -r * dist/ || true
          cp -r .* dist/ || true
          touch dist/.nojekyll  # Adiciona o arquivo .nojekyll para desabilitar o Jekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
          single-commit: true

